/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karyawan;

import Controller.dlm_data_karyawan;
import Controller.koneksi;
import MenuUtama.MenuUtama;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

//</editor-fold>
/**
 *
 * @author Farah Salsabila
 */
public class Data_Karyawan extends javax.swing.JFrame {

    private boolean sql;
    private DefaultTableModel model;

    /**
     * Creates new form Data_Karyawan
     */
    public Data_Karyawan() {
        initComponents();
        ViewData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txnip = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        cbagama = new javax.swing.JComboBox<>();
        rdlk = new javax.swing.JRadioButton();
        rdpr = new javax.swing.JRadioButton();
        rdmkh = new javax.swing.JRadioButton();
        rdbmkh = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txalamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nopon = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tmp_lahir = new javax.swing.JTextField();
        tgl_lahir = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        cbtambah = new javax.swing.JButton();
        cbsimpan = new javax.swing.JButton();
        cbedit = new javax.swing.JButton();
        cbhapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txjabatan = new javax.swing.JComboBox<>();
        level = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwoard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gaji = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        jLabel1.setText("DATA KARYAWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(51, 102, 0));

        jLabel12.setBackground(new java.awt.Color(51, 102, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DATA KARYAWAN");

        jLabel10.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status");

        jLabel11.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Agama");

        txnip.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnipActionPerformed(evt);
            }
        });

        txnama.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnamaActionPerformed(evt);
            }
        });

        cbagama.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Hindu", "Budha" }));
        cbagama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbagamaActionPerformed(evt);
            }
        });

        rdlk.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        rdlk.setText("Laki - Laki");

        rdpr.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        rdpr.setText("Perempuan");
        rdpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdprActionPerformed(evt);
            }
        });

        rdmkh.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        rdmkh.setText("Menikah");

        rdbmkh.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        rdbmkh.setText("Belum Menikah");
        rdbmkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbmkhActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" NIP");

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jabatan");

        jLabel8.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama ");

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Alamat");

        txalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txalamatActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("No.Telpon");

        jLabel14.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");

        nopon.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tempat Lahir");

        jLabel16.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tanggal Lahir");

        tgl_lahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_lahirActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Level");

        keluar.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        cbtambah.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        cbtambah.setText("Tambah");
        cbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtambahActionPerformed(evt);
            }
        });

        cbsimpan.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        cbsimpan.setText("Simpan");
        cbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsimpanActionPerformed(evt);
            }
        });

        cbedit.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        cbedit.setText("Edit");
        cbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbeditActionPerformed(evt);
            }
        });

        cbhapus.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        cbhapus.setText("Hapus");
        cbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhapusActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Jabatan", "Jenis Kelamin", "Agama", "Status", "Alamat", "Gaji Karyawan", "Tempat Lahir", "Tanggal Lahir", "Email", "No.Telpon", "Level"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Owner", "Karyawan" }));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Stokker", "Reseller" }));

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("passwoard");

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gaji_karyawan");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbtambah)
                                .addGap(18, 18, 18)
                                .addComponent(cbedit)
                                .addGap(18, 18, 18)
                                .addComponent(cbsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(cbhapus)
                                .addGap(18, 18, 18)
                                .addComponent(keluar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(panel1Layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel2)
                                                                    .addComponent(jLabel8)
                                                                    .addComponent(jLabel7)))
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel11))
                                                        .addGap(16, 16, 16))
                                                    .addGroup(panel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(60, 60, 60)))
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(panel1Layout.createSequentialGroup()
                                                        .addComponent(rdlk)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rdpr))
                                                    .addComponent(txjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txnip, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(panel1Layout.createSequentialGroup()
                                                        .addComponent(rdbmkh)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rdmkh))))
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(tmp_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                                .addGap(495, 495, 495)
                                                .addComponent(passwoard, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel9))
                                                    .addGroup(panel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(23, 23, 23)))
                                                .addGap(94, 94, 94)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nopon, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(gaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(txalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdlk)
                            .addComponent(rdpr)
                            .addComponent(jLabel13)
                            .addComponent(nopon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(261, 261, 261))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rdbmkh)
                            .addComponent(rdmkh))
                        .addGap(27, 27, 27)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tmp_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(passwoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbtambah)
                            .addComponent(cbedit)
                            .addComponent(cbsimpan)
                            .addComponent(cbhapus)
                            .addComponent(keluar)
                            .addComponent(jButton1))
                        .addGap(58, 58, 58)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnipActionPerformed

    private void txnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnamaActionPerformed

    private void txalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txalamatActionPerformed

    private void rdprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdprActionPerformed

    private void cbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtambahActionPerformed
        txnip.setText("");
        txnama.setText("");
        txjabatan.setSelectedItem(0);;
        buttonGroup1.clearSelection();
        cbagama.setSelectedItem(0);
        buttonGroup2.clearSelection();
        txalamat.setText("");
        tgl_lahir.setText("");
        tmp_lahir.setText("");
        nopon.setText("");
        email.setText("");
        level.setSelectedItem(0);
        username.setText("");
        passwoard.setText("");
        gaji.setText("");
    }//GEN-LAST:event_cbtambahActionPerformed

    private void cbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsimpanActionPerformed
        // TODO add your handling code here:
        dlm_data_karyawan ck = new dlm_data_karyawan();
        ck.nip = txnip.getText();
        ck.nama = txnama.getText();

        ck.jabatan = (String) txjabatan.getSelectedItem();
        if (rdlk.isSelected() == true) {
            ck.jenis_kelamin = "laki-laki";
        } else {
            ck.jenis_kelamin = "perempuan";
        }

        ck.agama = (String) cbagama.getSelectedItem();
        if (rdmkh.isSelected() == true) {
            ck.status = "menikah";
        } else {
            ck.status = "belum menikah";
        }

        ck.alamat = txalamat.getText();
        ck.tempat_lahir = tmp_lahir.getText();
        ck.tanggal_lahir = tgl_lahir.getText();
        ck.email = email.getText();
        ck.no_telpon = nopon.getText();
        ck.level = (String) level.getSelectedItem();
        ck.gaji_karyawan = gaji.getText();
        ck.username = username.getText();
        ck.passwoard = passwoard.getText();
        try {
            ck.simpan();
            JOptionPane.showMessageDialog(null, "Simpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ViewData();
    }//GEN-LAST:event_cbsimpanActionPerformed

    private void cbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbeditActionPerformed
        // TODO add your handling code here:
        dlm_data_karyawan ck = new dlm_data_karyawan();
        ck.nip = txnip.getText();
        ck.nama = txnama.getText();
        ck.jabatan = (String) txjabatan.getSelectedItem();
        if (rdlk.isSelected() == true) {
            ck.jenis_kelamin = "laki-laki";
        } else {
            ck.jenis_kelamin = "perempuan";
        }
        ck.agama = (String) cbagama.getSelectedItem();
        if (rdmkh.isSelected() == true) {
            ck.status = "menikah";
        } else {
            ck.status = "belum menikah";
        }
        ck.alamat = txalamat.getText();
        ck.tempat_lahir = tmp_lahir.getText();
        ck.tanggal_lahir = tgl_lahir.getText();
        ck.email = email.getText();
        ck.no_telpon = nopon.getText();
        ck.level = (String) level.getSelectedItem();
        ck.gaji_karyawan = gaji.getText();
        ck.username = username.getText();
        ck.passwoard = passwoard.getText();
        try {
            ck.edit();
            JOptionPane.showMessageDialog(null, "Teredit");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ViewData();
    }//GEN-LAST:event_cbeditActionPerformed

    private void cbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhapusActionPerformed
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes", "No"};
        int PromptResult = JOptionPane.showOptionDialog(null, " yakin mau hapus ?", "Massage", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if (PromptResult == 0) {
            dlm_data_karyawan ck = new dlm_data_karyawan();
            ck.nip = txnip.getText();
            try {
                ck.hapus();
                JOptionPane.showMessageDialog(null, "Terhapus");
                ViewData();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            System.out.println(sql);
            Connection con = (Connection) koneksi.getkoneksi();
            PreparedStatement pst;
        }

    }//GEN-LAST:event_cbhapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txnip.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txnama.setText(jTable1.getModel().getValueAt(row, 1).toString());
        String txjabatan = jTable1.getModel().getValueAt(row, 2).toString();
        Ambiljb(txjabatan);
        String jenis_kelamin = jTable1.getModel().getValueAt(row, 3).toString();
        Ambiljk(jenis_kelamin);
        String agama = jTable1.getModel().getValueAt(row, 4).toString();
        AmbilAgama(agama);
        String status = jTable1.getModel().getValueAt(row, 5).toString();
        AmbilStatus(status);
        txalamat.setText(jTable1.getModel().getValueAt(row, 6).toString());
        gaji.setText(jTable1.getModel().getValueAt(row, 7).toString());
        tmp_lahir.setText(jTable1.getModel().getValueAt(row, 8).toString());
        tgl_lahir.setText(jTable1.getModel().getValueAt(row, 9).toString());
        email.setText(jTable1.getModel().getValueAt(row, 10).toString());
        nopon.setText(jTable1.getModel().getValueAt(row, 11).toString());
        String level = jTable1.getModel().getValueAt(row, 12).toString();
        Ambillv(level);
        username.setText(jTable1.getModel().getValueAt(row, 13).toString());

//        int i = table.getSelectedRow();
//        if (i == -1) {
//            return;
//        }
//        System.out.println(1);
//        String id = (String) model.getValueAt(i, 0);
//        System.out.println(2);
//        System.out.println(id);
//        txnip.setText(id);
//        
//        String nama = (String) model.getValueAt(i, 1);
//        txnama.setText(nama);
//        
//        System.out.println(nama);
//        String jabatan = (String) model.getValueAt(i, 2);
//        txjabatan.setText(jabatan);
//        
//        System.out.println(jabatan);
//        
//        String jenis_kelamin = (String) model.getValueAt(i, 3);
//        
//        if ("laki-laki".equals(jenis_kelamin)){
//            System.out.println(jenis_kelamin);
//            rdlk.setSelected(true);
//        } else if ("perempuan".equals(jenis_kelamin)){
//            System.out.println(jenis_kelamin);
//            rdpr.setSelected(true);
//        }
//        
//        String agama = (String) model.getValueAt(i, 4);
//        cbagama.setSelectedItem(agama);
//        
//        System.out.println(agama);
//        
//        String status = (String) model.getValueAt(i, 5);
//        
//        if ("belum menikah".equals(status)){
//            System.out.println(status);
//            rdmkh.setSelected(true);
//        } else if ("menikah".equals(status)){
//            System.out.println(status);
//            rdbmkh.setSelected(true);
//        }
//
//        String alamat = (String) model.getValueAt(i, 6);
//        txalamat.setText(alamat);
//        System.out.println(alamat);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void cbagamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbagamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbagamaActionPerformed

    private void rdbmkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbmkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbmkhActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void tgl_lahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_lahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_lahirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuUtama fb = new MenuUtama();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

        int row = jTable1.getSelectedRow();
        txnip.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txnama.setText(jTable1.getModel().getValueAt(row, 1).toString());
        String txjabatan = jTable1.getModel().getValueAt(row, 2).toString();
        Ambiljb(txjabatan);
        String jenis_kelamin = jTable1.getModel().getValueAt(row, 3).toString();
        Ambiljk(jenis_kelamin);
        String agama = jTable1.getModel().getValueAt(row, 4).toString();
        AmbilAgama(agama);
        String status = jTable1.getModel().getValueAt(row, 5).toString();
        AmbilStatus(status);
        txalamat.setText(jTable1.getModel().getValueAt(row, 6).toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JButton cbedit;
    private javax.swing.JButton cbhapus;
    private javax.swing.JButton cbsimpan;
    private javax.swing.JButton cbtambah;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gaji;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextField nopon;
    private java.awt.Panel panel1;
    private javax.swing.JTextField passwoard;
    private javax.swing.JRadioButton rdbmkh;
    private javax.swing.JRadioButton rdlk;
    private javax.swing.JRadioButton rdmkh;
    private javax.swing.JRadioButton rdpr;
    private javax.swing.JTextField tgl_lahir;
    private javax.swing.JTextField tmp_lahir;
    private javax.swing.JTextField txalamat;
    private javax.swing.JComboBox<String> txjabatan;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnip;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void Ambiljk(String jk) {
        if (jk.equals("Laki-Laki")) {
            rdlk.setSelected(true);
        } else {
            rdpr.setSelected(true);
        }
    }

    private void AmbilStatus(String status) {
        if (status.equals("Menikah")) {
            rdmkh.setSelected(true);
        } else {
            rdbmkh.setSelected(true);
        }
    }

    private void AmbilAgama(String agama) {
        String[] ag = {"Islam", "Kristen", "Hindu", "Budha"};
        cbagama.removeAllItems();
        cbagama.addItem(agama);
        for (int i = 0; i < ag.length; i++) {
            if (!ag[i].equals(agama)) {
                cbagama.addItem(ag[i]);
            }
        }
    }

    private void ViewData() {
        dlm_data_karyawan ck = new dlm_data_karyawan();
        try {
            jTable1.setModel(DbUtils.resultSetToTableModel(ck.UpdateTable()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Ambiljb(String txtjabatan) {
        String[] ag = {"Manager", "Owner", "Karyawan"};
        txjabatan.removeAllItems();
        txjabatan.addItem(txtjabatan);
        for (int i = 0; i < ag.length; i++) {
            if (!ag[i].equals(txtjabatan)) {
                txjabatan.addItem(ag[i]);
            }
        }
    }

    private void Ambillv(String txtlevel) {
        String[] ag = {"Admin", "Kasir", "Stokker", "Laporan"};
        level.removeAllItems();
        level.addItem(txtlevel);
        for (int i = 0; i < ag.length; i++) {
            if (!ag[i].equals(txtlevel)) {
                level.addItem(ag[i]);
            }
        }
    }
}
